---
name: Task - Test Bridge

on:
  workflow_dispatch:
  workflow_call:

jobs:
  test_bridge:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      # selecting a toolchain either by action or manual `rustup` calls should happen
      # before the plugin, as the cache uses the current rustc version as its cache key
      - run: rustup show

      - uses: Swatinem/rust-cache@v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Run anvil
        run: |
          anvil </dev/null &>/dev/null &

      - name: Run madara
        run: |
          cd bin
          echo "Running madara...."
          ./run_madara.sh

      - name: Run tests
        run: |
          echo "Running test...."
          RUST_LOG=info cargo test -- --nocapture
